{{- if .Values.cronjob.enabled  }}

apiVersion: batch/v1
kind: CronJob

metadata:
  name: timestamp-cronjob
  namespace: {{ .Values.namespace }}

spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  SuccessfulJobsHistoryLimit: 3
  FailedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: timestamp-cronjob
        spec:
          serviceAccountName: {{ .Values.cronjob.serviceAccount.name }}
          restartPolicy: OnFailure
          containers:
            - name: timestamp
              image: busybox
              command:
              - /bin/sh
            - -c
            - date