namespace: test

image:
  repository: myacrdevops12345.azurecr.io/python-app
  tag: "6ae9ee508786809571e92d3d4c5d9532cf6149d7"

service:
  type: LoadBalancer
  port: 80

cronjob:
  schedule: "* * * * *"