namespace: test

image:
  repository: myacrdevops12345.azurecr.io/python-app
  tag: "a5233679acb0e20e47e0c1e07745614138e2ea87"

service:
  type: LoadBalancer
  port: 80

cronjob:
  schedule: "* * * * *"